<?php

/**
 * @file
 * Contains iframe_resizer.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iframe_resizer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iframe_resizer module.
    case 'help.page.iframe_resizer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides access to the iFrame Resizer javascript library') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * Adds the iframe-resizer javascript library(s) to the page.
 */
function iframe_resizer_page_attachments(array &$page) {
  $config = \Drupal::config('iframe_resizer.settings');

  // If this site will be hosting resizeable iframes, include the standard
  // iframe_resizer library file along with the JS to initilize the iframes.
  if ($config->get('iframe_resizer_usage.host')) {
    $page['#attached']['library'][] = 'iframe_resizer/init';

    $selectors = 'iframe';
    if ($config->get('iframe_resizer_advanced.target_type') === 'specific') {
      $selectors = implode(',', explode(PHP_EOL, $config->get('iframe_resizer_advanced.target_selectors')));
    }
    $advanced_settings['targetSelectors'] = $selectors;
    $advanced_settings['override_defaults'] = $config->get('iframe_resizer_advanced.override_defaults');
    $advanced_settings['options'] = $config->get('iframe_resizer_advanced.options');

    $page['#attached']['drupalSettings']['iframeResizer']['advanced'] = $advanced_settings;
  }

  // If this site will be hosted within a resizeable iframe, include the
  // iframe resizer library's content window library file and the config JS
  // file.
  if ($config->get('iframe_resizer_usage.hosted')) {
    $page['#attached']['library'][] = 'iframe_resizer/hosted';
    $page['#attached']['drupalSettings']['iframeResizer']['advancedHosted'] = $config->get('iframe_resizer_advanced_hosted_options');
  }
}
